# Generated by Django 3.2.5 on 2021-12-02 16:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('pswd', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=16)),
                ('state', models.SmallIntegerField(default=0)),
                ('claim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('token', models.CharField(max_length=64)),
                ('gen_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('op_to', models.SmallIntegerField(choices=[(0, 'entity'), (1, 'relation')])),
                ('operation', models.SmallIntegerField(choices=[(0, 'review passed'), (1, 'remove'), (2, 'modify'), (3, 'insert')])),
                ('element_id', models.IntegerField()),
                ('to_id', models.IntegerField(null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
