"""
Django settings for marker project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import sys
from pathlib import Path
from corsheaders.defaults import default_headers

# Retrieve variables from environment
try:
    production = os.environ['ENV'] == 'production'
    development = os.environ['ENV'] == 'development'
except KeyError:
    print('No ENV set, a \'production\' or \' development\' must be set as environment variable')
    sys.exit(-1)

try:
    if production:
        secret_key = os.environ['SECRET_KEY']
    else:
        secret_key = 'django-insecure-6bd4+f&4z6x8=&_ye8&b*v8759&m2%92y_@0h3-eiog=h5dc)('
except KeyError:
    print('No SECRET_KEY set, this environment variable must be set in production mode')
    sys.exit(-1)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

SECRET_KEY = secret_key

DEBUG = development

ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = False
CORS_ALLOW_HEADERS = ['token']

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.contenttypes',
    'project.apps.ProjectConfig',
    'user.apps.UserConfig'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marker.urls'

WSGI_APPLICATION = 'marker.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'DEVELOPMENT.sqlite3' if development else 'PRODUCTION.sqlite3',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
