# Generated by Django 3.2.8 on 2021-10-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_alter_project_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('pswd', models.CharField(max_length=256)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('token', models.CharField(max_length=256)),
                ('gen_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('op_to', models.SmallIntegerField(choices=[(0, 'Entity'), (1, 'Relation')])),
                ('operation', models.SmallIntegerField(choices=[(0, 'Reviewpassed'), (1, 'Remove'), (2, 'Modify')])),
                ('element_id', models.IntegerField()),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
