# Generated by Django 3.2.8 on 2021-11-10 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='from_id',
        ),
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.TimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='log',
            name='op_to',
            field=models.SmallIntegerField(choices=[(0, 'entity'), (1, 'relation')]),
        ),
        migrations.AlterField(
            model_name='log',
            name='operation',
            field=models.SmallIntegerField(choices=[(0, 'review passed'), (1, 'remove'), (2, 'modify'), (3, 'insert')]),
        ),
    ]
