# Generated by Django 3.2.5 on 2021-11-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_entity_fid'),
        ('user', '0004_alter_log_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='to_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pswd',
            field=models.CharField(max_length=64),
        ),
    ]
