# Generated by Django 3.2.8 on 2021-10-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
