# Generated by Django 3.2.8 on 2021-11-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_name',
            field=models.CharField(default='null', max_length=256),
        ),
    ]
