# Generated by Django 3.2.8 on 2021-11-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20211109_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='loc_end_column',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='loc_end_line',
        ),
    ]
