# Generated by Django 3.2.8 on 2021-11-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20211110_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='fid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project.file'),
        ),
    ]
