# Generated by Django 3.2.5 on 2021-11-27 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_entity_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.file'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='loc_end_column',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='entity',
            name='loc_end_line',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='entity',
            name='loc_start_column',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='entity',
            name='loc_start_line',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='lang',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='relation',
            name='from_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_entity', to='project.entity'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_entity', to='project.entity'),
        ),
    ]
