# Generated by Django 3.2.5 on 2021-12-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='loc_column',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='relation',
            name='loc_line',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.SmallIntegerField(),
        ),
    ]
